site_name: My Docs

repo_url: https://github.com/facumoyanosmf/mkdocs-prueba
repo_name: mkdocs-prueba
site_url: https://facumoyanosmf.github.io/mkdocs-prueba/
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Products: products.md
  - Page 1: 
    - Page 1.1: page1/page1.md
extra:
  version:
    provider: mike
    default: stable