site_name: My Docs

repo_url: https://github.com/facumoyanosmf/mkdocs-prueba
repo_name: mkdocs-prueba
site_url: https://facumoyanosmf.github.io/mkdocs-prueba/
nav:
  - Home: index.md
  - About: about.md
extra:
  version:
    provider: mike
    default: stable