name: Setup Docs
description: Setup MkDocs

runs:
  using: composite
  steps:
    - name: Setup Github Config
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
    - name: Install Dependencies
      run: |
        pip install mkdocs-material
        pip install pillow cairosvg
        pip install mike
        pip install mkdocs-glightbox
