name: Auto Reviewer

on:
  workflow_run:
    workflows: [Git Police]
    types:
      - completed

jobs:
  make-review:
    if: github.head_ref != 'develop'
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ github.event.workflow_run.head_repository.owner.login }}
      REPO_SLUG: ${{ github.event.workflow_run.head_repository.name }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ETENDOBOT_TOKEN: ${{ secrets.ETENDOBOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request number
        id: get_pr_number
        run: |
          GITHUB_SHA=$(git rev-parse HEAD)
          echo "Current commit SHA: $GITHUB_SHA"

          PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/commits/$GITHUB_SHA/pulls" \
            | jq -r '.[0].number')

          if [ "$PR_NUMBER" == "null" ] || [ -z "$PR_NUMBER" ]; then
            echo "No pull request found for this commit"
            exit 1
          fi

          echo "Pull request number: $PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Log pull request number
        run: echo "Pull request number is ${{ steps.get_pr_number.outputs.pr_number }}"

      - name: Run Docker container
        id: run-docker
        run: |
          printenv
          echo "-------------------------------------------------------------------------"
          echo ${{ env.DOCKERHUB_PASSWORD }} | docker login --username "${{ env.DOCKERHUB_USERNAME }}" --password-stdin
          docker run -d -p 5000:5000 -e REPO_API_TOKEN="${{ env.ETENDOBOT_TOKEN }}" -e PULL_REQUEST=${{ steps.get_pr_number.outputs.pr_number }} -e PROJECT=${{ env.PROJECT }} -e REPO_SLUG=${{ env.REPO_SLUG }} -e OPENAI_API_KEY="${{ env.OPENAI_API_KEY }}" etendo/code-reviewer:latest

      - name: Make Reviewer API call
        id: call-api
        run: |
          sleep 10s
          response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/github)
          if [ $response -ne 200 ]; then
            echo "API call failed with status code $response. This is likely an error related to the PR data, or an internal API error"
            echo "Response text:"
            cat response.txt
            exit 1
          fi
          echo "API call successful with status code $response"
          echo "Response text:"
          cat response.txt
