name: Build and Commit Docs

on:
    workflow_run:
      workflows: ['pages-build-deployment']
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docs
        uses: ./.github/actions/setup-docs

      - name: Run Script
        run: python compile_docs.py

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add compiled_docs.md
          git commit -m "Update compiled docs" || echo "No changes to commit"
          git push origin main
