name: pages-build-reusable

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  notify-on-pages-build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Pages Build Completion
        run: echo "Pages Build Workflow Completed"
