name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mike
      - run: pip install mkdocs-glightbox
      - run: mkdocs gh-deploy --force
      - name: Setup Github Config
        run: |
          git config --local user.name "${{ secrets.ETENDO_NAME }}"
          git config --local user.email "${{ secrets.DOCS_EMAIL }}"
      - run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest