name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup github config
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
      - name: Deploy Docs
        run: mkdocs gh-deploy

  deploy-versioning:
    needs: deploy-docs
    if: github.event_name == 'workflow_run' && github.event.workflow == 'pages-build-deployment' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Setup github config
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
      - name: Delay before Setup github config
        run: sleep 30
      - name: Setup Github Config
        run: |
          git config --local user.name "${{ secrets.ETENDO_NAME}}"
          git config --local user.email "${{ secrets.ETENDO_EMAIL}}"
      - name: Deploy Versioning
        run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest
