name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mike
      - run: pip install mkdocs-glightbox
      - name: Setup Github Config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

  deploy-docs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docs
        run: mkdocs gh-deploy

  deploy-versioning:
    needs:
      - deploy-docs
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Versioning
        run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest
