# ci.yml
name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docs
        uses: ./.github/workflows/setup-docs.yml
      - name: Deploy Docs
        run: mkdocs gh-deploy --force

  deploy-versioning:
    needs: deploy-docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docs
        uses: ./.github/workflows/setup-docs.yml
      - name: Deploy Versioning
        run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest
