name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup github config
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
      - name: Deploy Docs
        run: mkdocs gh-deploy

  deploy-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Wait Action
        uses: willgarcia/workflow-wait-action@0.1.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600
          interval: 10
          initial_delay: 30
      - name: Setup github config
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
      - name: Setup Github Config
        run: |
          git config --local user.name "${{ secrets.ETENDO_NAME }}"
          git config --local user.email "${{ secrets.ETENDO_EMAIL }}"
      - name: Deploy Versioning
        run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest