name: compile docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    compile-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Setup github config
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Setup Docs
            uses: ./.github/actions/setup-docs
    
          - name: Run Script
            run: python compile_docs.py
    
          - name: Commit Changes
            run: |
              git config --local user.email "actions@github.com"
              git config --local user.name "GitHub Actions"
              git add compiled_docs.md
              git commit -m "Update compiled docs file :page_facing_up:"
              git push origin main
