name: compile docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    compile-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Setup github config
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Check commit message format
            id: commit-check
            run: |
              commit_message=$(git log -1 --pretty=%B)
              if [[ "$commit_message" =~ ^Update\ \'compiled_docs\'\ file\ :page_facing_up:$ ]]; then
                echo "Skipping steps"
                echo "::set-output name=skip_steps::true"
              fi
            
                  
          - name: Run Script
            if: steps.commit-check.outputs.skip_steps != 'true'
            run: python compile_docs.py
    
          - name: Commit Changes
            if: steps.commit-check.outputs.skip_steps != 'true'
            run: |
              git config --local user.name "${{ secrets.ETENDO_NAME }}"
              git config --local user.email "${{ secrets.ETENDO_EMAIL }}"
              git pull origin main
              git add compiled_docs.md
              git commit -m "Update 'compiled_docs' file :page_facing_up:" || echo "No changes to commit"
              git push origin main
