name: compile docs

on:
  push:
    branches:
      - main

concurrency:
  group: compile-docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
    compile-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Setup github config
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Check commit message format
            run: |
              commit_message=$(git log -1 --pretty=%B)
              if [[ $commit_message =~ ^Update 'compiled_docs' file :page_facing_up:$ ]]; then
                echo "Commit message format is correct, skipping further steps."
                exit 78 # 78 is a neutral exit code indicating a skipped run
              else
                echo "Commit message format is incorrect, continuing with the workflow."
              fi
                  
          - name: Run Script
            run: python compile_docs.py
    
          - name: Commit Changes
            run: |
              git config --local user.name "${{ secrets.ETENDO_NAME }}"
              git config --local user.email "${{ secrets.ETENDO_EMAIL }}"
              git add compiled_docs.md
              git commit -m "Update 'compiled_docs' file :page_facing_up:" || echo "No changes to commit"
              git push origin main
