name: setup-docs
description: Setup for deploying documentation
runs:
  using: "composite"
  steps:
    - run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
    - run: pip install mkdocs-material
    - run: pip install pillow cairosvg
    - run: pip install mike
    - run: pip install mkdocs-glightbox