name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/setup-docs
      - run: mkdocs gh-deploy --force
  deploy-versioning:
    needs: deploy-docs
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/setup-docs
      - run: mike deploy --push --update-aliases ${{ secrets.DOCS_VERSION }} latest