name: versioning
on:
    release:
        types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Debugging info
        run: |
          git config --list
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "facundomoyano"
          git config --global user.email "facundo.moyano@smfconsulting.es"
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mike
      - run: pip install mkdocs-glightbox
      - run: mike deploy --push --update-aliases 23.1 latest
      - run: mike set-default --push latest
