name: versioning
on:
    release:
        types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mike
      - run: pip install mkdocs-glightbox
      - name: Setup Docs Deploy
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - run: ṕoetry run mike deploy --push --update-aliases 23.1 latest
      - run: ṕoetry run mike set-default --push latest
